// <auto-generated />
using System;
using Innovayse.Sheets.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Innovayse.Sheets.API.Data.Migrations
{
    [DbContext(typeof(SheetsDbContext))]
    [Migration("20260709084202_AddSharingTables")]
    partial class AddSharingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Innovayse.Sheets.API.Data.Entities.Cell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Col")
                        .HasColumnType("integer");

                    b.Property<string>("FormatJson")
                        .HasColumnType("text");

                    b.Property<string>("RawValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<Guid>("SheetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SheetId", "Row", "Col")
                        .IsUnique();

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("Innovayse.Sheets.API.Data.Entities.SharingLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpreadsheetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SpreadsheetId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Links");
                });

            modelBuilder.Entity("Innovayse.Sheets.API.Data.Entities.Sheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpreadsheetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpreadsheetId");

                    b.ToTable("Sheets");
                });

            modelBuilder.Entity("Innovayse.Sheets.API.Data.Entities.Spreadsheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Spreadsheets");
                });

            modelBuilder.Entity("Innovayse.Sheets.API.Data.Entities.SpreadsheetShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpreadsheetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpreadsheetId", "UserId")
                        .IsUnique();

                    b.ToTable("Shares");
                });

            modelBuilder.Entity("Innovayse.Sheets.API.Data.Entities.Cell", b =>
                {
                    b.HasOne("Innovayse.Sheets.API.Data.Entities.Sheet", null)
                        .WithMany()
                        .HasForeignKey("SheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Innovayse.Sheets.API.Data.Entities.SharingLink", b =>
                {
                    b.HasOne("Innovayse.Sheets.API.Data.Entities.Spreadsheet", null)
                        .WithMany()
                        .HasForeignKey("SpreadsheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Innovayse.Sheets.API.Data.Entities.Sheet", b =>
                {
                    b.HasOne("Innovayse.Sheets.API.Data.Entities.Spreadsheet", null)
                        .WithMany()
                        .HasForeignKey("SpreadsheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Innovayse.Sheets.API.Data.Entities.SpreadsheetShare", b =>
                {
                    b.HasOne("Innovayse.Sheets.API.Data.Entities.Spreadsheet", null)
                        .WithMany()
                        .HasForeignKey("SpreadsheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
